name: CI

on:
  pull_request:
    branches: [main, release]

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Restore
        run: dotnet restore JmapKit.sln

      - name: Build
        run: dotnet build JmapKit.sln --no-restore -warnaserror

      - name: Test
        run: dotnet test JmapKit.sln --no-build
